const WinterCollectionTab=[
        {
            id:1,
            url:"https://i.pinimg.com/1200x/d7/07/4b/d7074b42cf01828a425820260ed078df.jpg",
            title:,
            description:,
            price:
        },
        {
            id:2,
            url:,
            title:,
            description:,
            price:
        },
        {
            id:3,
            url:,
            title:,
            description:,
            price:
        },
        {
            id:4,
            url:,
            title:,
            description:,
            price:
        },
        {
            id:5,
            url:,
            title:,
            description:,
            price:
        },
        {
            id:6,
            url:,
            title:,
            description:,
            price:
        },
        {
            id:7,
            url:,
            title:,
            description:,
            price:
        },
        {
            id:8,
            url:,
            title:,
            description:,
            price:
        },
        {
            id:9,
            url:,
            title:,
            description:,
            price:
        }
    ]